function execute() {
    return Response.success([
        {title: "https://beeng.net/the-loai/romance-8", input: "Romance", script: "gen.js"},
        {title: "https://beeng.net/the-loai/comedy-4", input: "Comedy", script: "gen.js"},
        {title: "https://beeng.net/the-loai/action-1", input: "Action", script: "gen.js"},
        {title: "https://beeng.net/the-loai/manhua-9", input: "Manhua", script: "gen.js"},
        {title: "https://beeng.net/the-loai/truyen-mau-11", input: "Truyện Màu", script: "gen.js"},
        {title: "https://beeng.net/the-loai/fantasy-5", input: "Fantasy", script: "gen.js"},
        {title: "https://beeng.net/the-loai/drama-22", input: "Drama", script: "gen.js"},
        {title: "https://beeng.net/the-loai/adventure-2", input: "Adventure", script: "gen.js"},
        {title: "https://beeng.net/the-loai/school-life-16", input: "School Life", script: "gen.js"},
        {title: "https://beeng.net/the-loai/slice-of-life-25", input: "Slice of life", script: "gen.js"},
        {title: "https://beeng.net/the-loai/shoujo-21", input: "Shoujo", script: "gen.js"},
        {title: "https://beeng.net/the-loai/shounen-17", input: "Shounen", script: "gen.js"},
        {title: "https://beeng.net/the-loai/supernatural-20", input: "Supernatural", script: "gen.js"},
        {title: "https://beeng.net/the-loai/mystery-10", input: "Mystery", script: "gen.js"},
        {title: "https://beeng.net/the-loai/seinen-47", input: "Seinen", script: "gen.js"},
        {title: "https://beeng.net/the-loai/manga-18", input: "Manga", script: "gen.js"},
        {title: "https://beeng.net/the-loai/ngon-tinh-13", input: "Ngôn Tình", script: "gen.js"},
        {title: "https://beeng.net/the-loai/horror-19", input: "Horror", script: "gen.js"},
        {title: "https://beeng.net/the-loai/harem-6", input: "Harem", script: "gen.js"},
        {title: "https://beeng.net/the-loai/martial-arts-7", input: "Martial Arts", script: "gen.js"},
        {title: "https://beeng.net/the-loai/webtoon-35", input: "Webtoon", script: "gen.js"},
        {title: "https://beeng.net/the-loai/historical-23", input: "Historical", script: "gen.js"},
        {title: "https://beeng.net/the-loai/manhwa-33", input: "Manhwa", script: "gen.js"},
        {title: "https://beeng.net/the-loai/sci-fi-27", input: "Sci-fi", script: "gen.js"},
        {title: "https://beeng.net/the-loai/one-shot-28", input: "One Shot", script: "gen.js"},
        {title: "https://beeng.net/the-loai/xuyen-khong-12", input: "Xuyên Không", script: "gen.js"},
        {title: "https://beeng.net/the-loai/tragedy-24", input: "Tragedy", script: "gen.js"},
        {title: "https://beeng.net/the-loai/co-dai-57", input: "Cổ Đại", script: "gen.js"},
        {title: "https://beeng.net/the-loai/chuyen-sinh-3", input: "Chuyển Sinh", script: "gen.js"},
        {title: "https://beeng.net/the-loai/smut-45", input: "Smut", script: "gen.js"},
        {title: "https://beeng.net/the-loai/doujinshi-42", input: "Doujinshi", script: "gen.js"},
        {title: "https://beeng.net/the-loai/adult-46", input: "Adult", script: "gen.js"},
        {title: "https://beeng.net/the-loai/psychological-52", input: "Psychological", script: "gen.js"},
        {title: "https://beeng.net/the-loai/truyen-han-manhwa-32", input: "Truyện Hàn (Manhwa)", script: "gen.js"},
        {title: "https://beeng.net/the-loai/yuri-37", input: "Yuri", script: "gen.js"},
        {title: "https://beeng.net/the-loai/shoujo-ai-29", input: "Shoujo Ai", script: "gen.js"},
        {title: "https://beeng.net/the-loai/mature-59", input: "Mature", script: "gen.js"},
        {title: "https://beeng.net/the-loai/beengnet-80", input: "Beeng.net", script: "gen.js"},
        {title: "https://beeng.net/the-loai/josei-44", input: "Josei", script: "gen.js"},
        {title: "https://beeng.net/the-loai/comic-36", input: "Comic", script: "gen.js"},
        {title: "https://beeng.net/the-loai/truong-thanh-18-26", input: "Trưởng thành 18+", script: "gen.js"},
        {title: "https://beeng.net/the-loai/gender-bender-48", input: "Gender Bender", script: "gen.js"},
        {title: "https://beeng.net/the-loai/shounen-ai-31", input: "Shounen Ai", script: "gen.js"},
        {title: "https://beeng.net/the-loai/psycho-30", input: "Psycho", script: "gen.js"},
        {title: "https://beeng.net/the-loai/yaoi-41", input: "Yaoi", script: "gen.js"},
        {title: "https://beeng.net/the-loai/soft-yaoi-51", input: "Soft Yaoi", script: "gen.js"},
        {title: "https://beeng.net/the-loai/dam-my-62", input: "Đam Mỹ", script: "gen.js"},
        {title: "https://beeng.net/the-loai/sports-34", input: "Sports", script: "gen.js"},
        {title: "https://beeng.net/the-loai/isekaidi-gioitrong-sinh-56", input: "Isekai/Dị giới/Trọng sinh", script: "gen.js"},
        {title: "https://beeng.net/the-loai/mecha-50", input: "Mecha", script: "gen.js"},
        {title: "https://beeng.net/the-loai/magic-64", input: "Magic", script: "gen.js"},
        {title: "https://beeng.net/the-loai/anime-14", input: "Anime", script: "gen.js"},
        {title: "https://beeng.net/the-loai/18-72", input: "18+", script: "gen.js"},
        {title: "https://beeng.net/the-loai/full-mau-65", input: "Full màu", script: "gen.js"},
        {title: "https://beeng.net/the-loai/16-58", input: "16+", script: "gen.js"},
        {title: "https://beeng.net/the-loai/huyen-huyen-60", input: "Huyền Huyễn", script: "gen.js"},
        {title: "https://beeng.net/the-loai/truyen-viet-49", input: "Truyền Việt", script: "gen.js"},
        {title: "https://beeng.net/the-loai/trinh-tham-74", input: "Trinh Thám", script: "gen.js"},
        {title: "https://beeng.net/the-loai/game-73", input: "Game", script: "gen.js"},
        {title: "https://beeng.net/the-loai/trong-sinh-61", input: "Trọng Sinh", script: "gen.js"},
        {title: "https://beeng.net/the-loai/viet-nam-70", input: "Việt Nam", script: "gen.js"},
        {title: "https://beeng.net/the-loai/music-71", input: "Music", script: "gen.js"},
        {title: "https://beeng.net/the-loai/he-thong-79", input: "Hệ Thống", script: "gen.js"},
        {title: "https://beeng.net/the-loai/ntr-66", input: "NTR", script: "gen.js"},
        {title: "https://beeng.net/the-loai/trap-crossdressing-76", input: "Trap (Crossdressing)", script: "gen.js"},
        {title: "https://beeng.net/the-loai/tu-chan-tu-tien-68", input: "Tu chân - tu tiên", script: "gen.js"}
    ]);
}