function execute() {
    return Response.success([
        {title: "Tất cả", input: "https://saytruyen.com/danh-sach-truyen.html", script: "gen.js"},
        {title: "18+", input: "https://saytruyen.com/danh-sach-truyen-the-loai-18.html", script: "gen.js"},
        {title: "Action", input: "https://saytruyen.com/danh-sach-truyen-the-loai-action.html", script: "gen.js"},
        {title: "Adult", input: "https://saytruyen.com/danh-sach-truyen-the-loai-adult.html", script: "gen.js"},
        {title: "Adventure", input: "https://saytruyen.com/danh-sach-truyen-the-loai-adventure.html", script: "gen.js"},
        {title: "Anime", input: "https://saytruyen.com/danh-sach-truyen-the-loai-anime.html", script: "gen.js"},
        {title: "Chuyển Sinh", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Chuyển Sinh.html", script: "gen.js"},
        {title: "Comedy", input: "https://saytruyen.com/danh-sach-truyen-the-loai-comedy.html", script: "gen.js"},
        {title: "Comic", input: "https://saytruyen.com/danh-sach-truyen-the-loai-comic.html", script: "gen.js"},
        {title: "Cooking", input: "https://saytruyen.com/danh-sach-truyen-the-loai-cooking.html", script: "gen.js"},
        {title: "Cổ Đại", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Cổ Đại.html", script: "gen.js"},
        {title: "Doujinshi", input: "https://saytruyen.com/danh-sach-truyen-the-loai-doujinshi.html", script: "gen.js"},
        {title: "Drama", input: "https://saytruyen.com/danh-sach-truyen-the-loai-drama.html", script: "gen.js"},
        {title: "Đam Mỹ", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Đam Mỹ.html", script: "gen.js"},
        {title: "Ecchi", input: "https://saytruyen.com/danh-sach-truyen-the-loai-ecchi.html", script: "gen.js"},
        {title: "Fantasy", input: "https://saytruyen.com/danh-sach-truyen-the-loai-fantasy.html", script: "gen.js"},
        {title: "Gender Bender", input: "https://saytruyen.com/danh-sach-truyen-the-loai-gender bender.html", script: "gen.js"},
        {title: "Harem", input: "https://saytruyen.com/danh-sach-truyen-the-loai-harem.html", script: "gen.js"},
        {title: "Historical", input: "https://saytruyen.com/danh-sach-truyen-the-loai-historical.html", script: "gen.js"},
        {title: "Horror", input: "https://saytruyen.com/danh-sach-truyen-the-loai-horror.html", script: "gen.js"},
        {title: "Isekai", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Isekai.html", script: "gen.js"},
        {title: "Josei", input: "https://saytruyen.com/danh-sach-truyen-the-loai-josei.html", script: "gen.js"},
        {title: "Live action", input: "https://saytruyen.com/danh-sach-truyen-the-loai-live action.html", script: "gen.js"},
        {title: "Manga", input: "https://saytruyen.com/danh-sach-truyen-the-loai-manga.html", script: "gen.js"},
        {title: "Manhua", input: "https://saytruyen.com/danh-sach-truyen-the-loai-manhua.html", script: "gen.js"},
        {title: "Manhwa", input: "https://saytruyen.com/danh-sach-truyen-the-loai-manhwa.html", script: "gen.js"},
        {title: "Martial Arts", input: "https://saytruyen.com/danh-sach-truyen-the-loai-martial art.html", script: "gen.js"},
        {title: "Mature", input: "https://saytruyen.com/danh-sach-truyen-the-loai-mature.html", script: "gen.js"},
        {title: "Mecha", input: "https://saytruyen.com/danh-sach-truyen-the-loai-mecha.html", script: "gen.js"},
        {title: "Mystery", input: "https://saytruyen.com/danh-sach-truyen-the-loai-mystery.html", script: "gen.js"},
        {title: "Ngôn Tình", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Ngôn Tình.html", script: "gen.js"},
        {title: "One shot", input: "https://saytruyen.com/danh-sach-truyen-the-loai-one shot.html", script: "gen.js"},
        {title: "Psychological", input: "https://saytruyen.com/danh-sach-truyen-the-loai-psychological.html", script: "gen.js"},
        {title: "Romance", input: "https://saytruyen.com/danh-sach-truyen-the-loai-romance.html", script: "gen.js"},
        {title: "School Life", input: "https://saytruyen.com/danh-sach-truyen-the-loai-school life.html", script: "gen.js"},
        {title: "Sci-fi", input: "https://saytruyen.com/danh-sach-truyen-the-loai-sci-fi.html", script: "gen.js"},
        {title: "Seinen", input: "https://saytruyen.com/danh-sach-truyen-the-loai-seinen.html", script: "gen.js"},
        {title: "Shoujo", input: "https://saytruyen.com/danh-sach-truyen-the-loai-shoujo.html", script: "gen.js"},
        {title: "Shoujo Ai", input: "https://saytruyen.com/danh-sach-truyen-the-loai-shoujou ai.html", script: "gen.js"},
        {title: "Shounen", input: "https://saytruyen.com/danh-sach-truyen-the-loai-shounen.html", script: "gen.js"},
        {title: "Shounen Ai", input: "https://saytruyen.com/danh-sach-truyen-the-loai-shounen ai.html", script: "gen.js"},
        {title: "Slice of Life", input: "https://saytruyen.com/danh-sach-truyen-the-loai-slice of life.html", script: "gen.js"},
        {title: "Smut", input: "https://saytruyen.com/danh-sach-truyen-the-loai-smut.html", script: "gen.js"},
        {title: "Soft Yaoi", input: "https://saytruyen.com/danh-sach-truyen-the-loai-soft yaoi.html", script: "gen.js"},
        {title: "Soft Yuri", input: "https://saytruyen.com/danh-sach-truyen-the-loai-soft yuri.html", script: "gen.js"},
        {title: "Sports", input: "https://saytruyen.com/danh-sach-truyen-the-loai-sports.html", script: "gen.js"},
        {title: "Supernatural", input: "https://saytruyen.com/danh-sach-truyen-the-loai-supernatural.html", script: "gen.js"},
        {title: "Tragedy", input: "https://saytruyen.com/danh-sach-truyen-the-loai-tragedy.html", script: "gen.js"},
        {title: "Trinh Thám", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Trinh Thám.html", script: "gen.js"},
        {title: "Truyện scan", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Truyện scan.html", script: "gen.js"},
        {title: "Truyện Màu", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Truyện Màu.html", script: "gen.js"},
        {title: "Webtoon", input: "https://saytruyen.com/danh-sach-truyen-the-loai-webtoon.html", script: "gen.js"},
        {title: "Xuyên Không", input: "https://saytruyen.com/danh-sach-truyen-the-loai-Xuyên Không.html", script: "gen.js"},
    ]);
}